### ISSUE TITLE
NullPointerException at .MethodBody.toString() and it is obvious

### ISSUE THREAD

**Issue by KYHSGeekCode** [TomSmartBishop/facile-api#6]
The library throws null pointer exception when I call methodbody.toString().

`java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String at.pollaknet.api.facile.renderer.LanguageRenderer.renderAsReference(at.pollaknet.api.facile.symtab.symbols.Field)' on a null object reference
        at at.pollaknet.api.facile.metamodel.entries.FieldEntry.renderAsReference(FieldEntry.java:188)
        at at.pollaknet.api.facile.code.instruction.object.Stsfld.render(Stsfld.java:16)
        at at.pollaknet.api.facile.code.MethodBody.toString(MethodBody.java:695)`

**Comment by KYHSGeekCode** [comment]
Especially on constructor.

**Comment by KYHSGeekCode** [comment]
Maybe the methodbody instance needs to reference a FacileReflector object. Now I have a workaround for it, but you may need a pull request or sthing.
